name = "2jammers/spr"
version = "2.1.0"
description = "Small and fast motion library"
authors = ["Fraktality"]
repository = "https://github.com/Fraktality/spr"
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
